vlc = 5; //velocidade
hvlc = 0; //velocidade horizontal
vvlc = 0; //velocidade vertical
grv = 0.4; //gravidadde
distancia = 60;
image_speed = 0.4; //velocidade de reprodução de uma animação
vidaChefeAgua = 2;
global.chefesAguaVivos = instance_number(obj_chefe_agua);
alarm[0] = 0;