vlc = 5; //velocidade
hvlc = 0; //velocidade horizontal
vvlc = 0; //velocidade vertical
grv = 0.4; //gravidadde
distancia = 90;
image_speed = 0.4; //velocidade de reprodução de uma animação
vidaChefeMetal = 2;
global.chefesMetalVivos = instance_number(obj_chefe_metal);
alarm[0] = 0;