vlc = 5; //velocidade
hvlc = 0; //velocidade horizontal
vvlc = 0; //velocidade vertical
grv = 0.4; //gravidadde
distancia = 50;
image_speed = 0.4; //velocidade de reprodução de uma animação
vidaChefeTerra = 2;
global.chefesTerraVivos = instance_number(obj_chefe_terra); 
alarm[0] = 0;