vlc = 5; //velocidade
hvlc = 0; //velocidade horizontal
vvlc = 0; //velocidade vertical
grv = 0.4; //gravidadde
distancia = 120;
image_speed = 0.4; //velocidade de reprodução de uma animação
vidaChefeFogo = 2;
global.chefesFogoVivos = instance_number(obj_chefe_fogo); 
alarm[0] = 0;