vlc = 5; //velocidade
hvlc = 0; //velocidade horizontal
vvlc = 0; //velocidade vertical
grv = 0.4; //gravidadde
distancia = 140;
image_speed = 0.4; //velocidade de reprodução de uma animação
vidaChefeCristal = 2;
global.chefesCristalVivos = instance_number(obj_chefe_cristal); 
alarm[0] = 0;